### ISSUE TITLE
Situation Reports: release TODO

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#221]
- [x] Edit sitemap
- [x] Redirect old routes, including `situation-reports-demo` -- see #214 
- [x] Edit changelog
- [x] Replace SituationReports, SituationReport
- [x] Add genomics to homepage
- [x] Remove console.logs
- [x] Change "/situation-report" to "/situation-reports"
