### ISSUE TITLE
Version 3 checklist

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#299]
# API
- [x] Update dev mapping --> prod
- [x] Update all handlers --> prod

# Data
- [x] Merge dev branch of curated mutations file into main

# Front-end
- [ ] Update homepage w/ location reports
- [x] Update changelog
- [x] Update nav bar w/ location reports
- [ ] (maybe) #300
